services:
  - type: web
    name: mv-pulse
    runtime: python
    plan: free
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python seed_data.py
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mv-pulse-db
          property: connectionString

databases:
  - name: mv-pulse-db
    plan: free