"""Initial persistence schema

Revision ID: 2513dc99da7b
Revises: 
Create Date: 2026-04-18 16:52:47.698622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2513dc99da7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video_path', sa.String(length=300), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('watch_time', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('creator_score', sa.Float(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('voice_replies', sa.Integer(), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('debate_score', sa.Float(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('community_score', sa.Float(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('agree_count', sa.Integer(), nullable=True),
    sa.Column('disagree_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('creator_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('tier_name', sa.String(length=80), nullable=False),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('founder_badges_enabled', sa.Boolean(), nullable=False),
    sa.Column('founder_badge_limit', sa.Integer(), nullable=False),
    sa.Column('earnings_balance_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creator_user_id', 'tier_name', name='uq_creator_subscription_tier')
    )
    with op.batch_alter_table('creator_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_subscription_creator_user_id'), ['creator_user_id'], unique=False)

    op.create_table('export_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_project_user_id'), ['user_id'], unique=False)

    op.create_table('follow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follow_followed_id'), ['followed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follow_follower_id'), ['follower_id'], unique=False)

    op.create_table('user_social_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=400), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('primary_language_code', sa.String(length=10), nullable=False),
    sa.Column('secondary_language_code', sa.String(length=10), nullable=False),
    sa.Column('voice_style', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_social_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_social_profile_user_id'), ['user_id'], unique=True)

    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_path', sa.String(length=400), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=400), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('alternate_language_code', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('transcript_summary', sa.Text(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares_count', sa.Integer(), nullable=False),
    sa.Column('watch_time', sa.Integer(), nullable=False),
    sa.Column('creator_score', sa.Float(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('voice_replies', sa.Integer(), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('debate_score', sa.Float(), nullable=False),
    sa.Column('community_score', sa.Float(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_creator_id'), ['creator_id'], unique=False)

    op.create_table('text_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_comment_video_id'), ['video_id'], unique=False)

    op.create_table('voice_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_reply_id', sa.Integer(), nullable=True),
    sa.Column('client_token', sa.String(length=128), nullable=True),
    sa.Column('audio_url', sa.String(length=400), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('controversy_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_reply_id'], ['voice_reply.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_reply_client_token'), ['client_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_reply_parent_reply_id'), ['parent_reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_reply_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_reply_video_id'), ['video_id'], unique=False)

    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('reel_id', sa.Integer(), nullable=True),
    sa.Column('voice_reply_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('video_id IS NOT NULL OR reel_id IS NOT NULL OR voice_reply_id IS NOT NULL', name='ck_like_has_target'),
    sa.ForeignKeyConstraint(['reel_id'], ['reel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reel_id', name='uq_like_user_reel'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_like_user_video'),
    sa.UniqueConstraint('user_id', 'voice_reply_id', name='uq_like_user_voice_reply')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_like_reel_id'), ['reel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_like_voice_reply_id'), ['voice_reply_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('voice_reply_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_voice_reply_id'), ['voice_reply_id'], unique=False)

    op.create_table('premium_voice_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('highlighted_reply_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=40), nullable=False),
    sa.Column('session_kind', sa.String(length=40), nullable=False),
    sa.Column('tier_name', sa.String(length=80), nullable=True),
    sa.Column('entry_price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('founder_badges_enabled', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('participant_cap', sa.Integer(), nullable=False),
    sa.Column('earnings_balance_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['highlighted_reply_id'], ['voice_reply.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('premium_voice_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_premium_voice_room_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_voice_room_highlighted_reply_id'), ['highlighted_reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_premium_voice_room_video_id'), ['video_id'], unique=False)

    op.create_table('save',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('reel_id', sa.Integer(), nullable=True),
    sa.Column('voice_reply_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('video_id IS NOT NULL OR reel_id IS NOT NULL OR voice_reply_id IS NOT NULL', name='ck_save_has_target'),
    sa.ForeignKeyConstraint(['reel_id'], ['reel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reel_id', name='uq_save_user_reel'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_save_user_video'),
    sa.UniqueConstraint('user_id', 'voice_reply_id', name='uq_save_user_voice_reply')
    )
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_save_reel_id'), ['reel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_save_voice_reply_id'), ['voice_reply_id'], unique=False)

    op.create_table('thread_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('root_reply_id', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('cluster_label', sa.String(length=80), nullable=False),
    sa.Column('controversy_score', sa.Float(), nullable=False),
    sa.Column('reply_velocity', sa.Float(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['root_reply_id'], ['voice_reply.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'root_reply_id', name='uq_thread_summary_scope')
    )
    with op.batch_alter_table('thread_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_summary_root_reply_id'), ['root_reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_summary_video_id'), ['video_id'], unique=False)

    op.create_table('voice_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('embedding_vector_json', sa.Text(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_embedding_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_embedding_voice_reply_id'), ['voice_reply_id'], unique=True)

    op.create_table('voice_insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_reply_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_label', sa.String(length=80), nullable=False),
    sa.Column('topic_confidence', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('controversy_score', sa.Float(), nullable=False),
    sa.Column('tone_label', sa.String(length=80), nullable=False),
    sa.Column('energy_score', sa.Float(), nullable=False),
    sa.Column('replay_signal', sa.Float(), nullable=False),
    sa.Column('intelligence_score', sa.Float(), nullable=False),
    sa.Column('moderation_state', sa.String(length=40), nullable=False),
    sa.Column('processing_state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_insight_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_insight_voice_reply_id'), ['voice_reply_id'], unique=True)

    op.create_table('subscriber_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('subscriber_user_id', sa.Integer(), nullable=False),
    sa.Column('creator_subscription_id', sa.Integer(), nullable=True),
    sa.Column('premium_room_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.String(length=40), nullable=False),
    sa.Column('tier_name', sa.String(length=80), nullable=True),
    sa.Column('founder_badge_granted', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_subscription_id'], ['creator_subscription.id'], ),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['premium_room_id'], ['premium_voice_room.id'], ),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriber_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriber_access_creator_subscription_id'), ['creator_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_access_creator_user_id'), ['creator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_access_premium_room_id'), ['premium_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_access_subscriber_user_id'), ['subscriber_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriber_access_video_id'), ['video_id'], unique=False)

    op.create_table('tip_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('voice_reply_id', sa.Integer(), nullable=True),
    sa.Column('premium_room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['premium_room_id'], ['premium_voice_room.id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.ForeignKeyConstraint(['voice_reply_id'], ['voice_reply.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tip_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tip_transaction_premium_room_id'), ['premium_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_transaction_receiver_user_id'), ['receiver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_transaction_sender_user_id'), ['sender_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_transaction_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tip_transaction_voice_reply_id'), ['voice_reply_id'], unique=False)

    op.create_table('voice_room_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premium_room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('has_paid_entry', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['premium_room_id'], ['premium_voice_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('premium_room_id', 'user_id', name='uq_voice_room_user')
    )
    with op.batch_alter_table('voice_room_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_room_participant_premium_room_id'), ['premium_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_room_participant_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_room_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_room_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_voice_room_participant_premium_room_id'))

    op.drop_table('voice_room_participant')
    with op.batch_alter_table('tip_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tip_transaction_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_tip_transaction_video_id'))
        batch_op.drop_index(batch_op.f('ix_tip_transaction_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_tip_transaction_receiver_user_id'))
        batch_op.drop_index(batch_op.f('ix_tip_transaction_premium_room_id'))

    op.drop_table('tip_transaction')
    with op.batch_alter_table('subscriber_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriber_access_video_id'))
        batch_op.drop_index(batch_op.f('ix_subscriber_access_subscriber_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriber_access_premium_room_id'))
        batch_op.drop_index(batch_op.f('ix_subscriber_access_creator_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriber_access_creator_subscription_id'))

    op.drop_table('subscriber_access')
    with op.batch_alter_table('voice_insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_insight_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_voice_insight_user_id'))

    op.drop_table('voice_insight')
    with op.batch_alter_table('voice_embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_embedding_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_voice_embedding_user_id'))

    op.drop_table('voice_embedding')
    with op.batch_alter_table('thread_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_summary_video_id'))
        batch_op.drop_index(batch_op.f('ix_thread_summary_root_reply_id'))

    op.drop_table('thread_summary')
    with op.batch_alter_table('save', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_save_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_save_video_id'))
        batch_op.drop_index(batch_op.f('ix_save_user_id'))
        batch_op.drop_index(batch_op.f('ix_save_reel_id'))

    op.drop_table('save')
    with op.batch_alter_table('premium_voice_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_premium_voice_room_video_id'))
        batch_op.drop_index(batch_op.f('ix_premium_voice_room_highlighted_reply_id'))
        batch_op.drop_index(batch_op.f('ix_premium_voice_room_creator_user_id'))

    op.drop_table('premium_voice_room')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_notification_video_id'))
        batch_op.drop_index(batch_op.f('ix_notification_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_actor_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_like_voice_reply_id'))
        batch_op.drop_index(batch_op.f('ix_like_video_id'))
        batch_op.drop_index(batch_op.f('ix_like_user_id'))
        batch_op.drop_index(batch_op.f('ix_like_reel_id'))

    op.drop_table('like')
    with op.batch_alter_table('voice_reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_reply_video_id'))
        batch_op.drop_index(batch_op.f('ix_voice_reply_user_id'))
        batch_op.drop_index(batch_op.f('ix_voice_reply_parent_reply_id'))
        batch_op.drop_index(batch_op.f('ix_voice_reply_client_token'))

    op.drop_table('voice_reply')
    with op.batch_alter_table('text_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_comment_video_id'))
        batch_op.drop_index(batch_op.f('ix_text_comment_user_id'))

    op.drop_table('text_comment')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_creator_id'))

    op.drop_table('video')
    with op.batch_alter_table('user_social_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_social_profile_user_id'))

    op.drop_table('user_social_profile')
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follow_followed_id'))

    op.drop_table('follow')
    with op.batch_alter_table('export_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_project_user_id'))

    op.drop_table('export_project')
    with op.batch_alter_table('creator_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_subscription_creator_user_id'))

    op.drop_table('creator_subscription')
    op.drop_table('user')
    op.drop_table('reel')
    # ### end Alembic commands ###
